### ISSUE TITLE
MD-10: Set up the database

### ISSUE THREAD

**Issue by Danny-Mus** [Danny-Mus/master-dex#11]
# As a PO i want the database to be created in order to be able to save data from users

## Tasks
What are the tasks/todo's for this user story

- [x] create a database design
- [x] make database conection
- [x] make the database
