### ISSUE TITLE
MD-05: Create general styling

### ISSUE THREAD

**Issue by Danny-Mus** [Danny-Mus/master-dex#6]
# MD-05: As a PO i want general styling for the project

## Tasks
What are the tasks/todo's for this user story

- [x] Make design guidelines

- Mixins
- [x] Create button mixin
- [x] Create input mixin
- [x] Create radiobutton mixin
- [x] Create font mixin

- Variables
- [x] Create variables (colors, fonts)

- Normalize
- [x] Create normalize

## Ready for Review?
- You need 2 thumbs off
- Build (code and design) are according to Definition Of Done (see dod.md)
