### ISSUE TITLE
MD-07: Team creation

### ISSUE THREAD

**Issue by Danny-Mus** [Danny-Mus/master-dex#8]
# MD-07: As a PO i want to be able to create an team of pokemons i chose.

## Tasks
What are the tasks/todo's for this user story

- [x] Create page for team creation
- [ ] Be able to chose team name when creating teams

### If database allows it
- [ ] Display list of all teams with option 'Public'
- [ ] Be able to save teams in the database
- [ ] Public/Private option when creating or editing teams

## Ready for Review?
- You need 2 thumbs off
- Build (code and design) are according to Definition Of Done (see dod.md)
