### ISSUE TITLE
MD-08: indepth pokemon info

### ISSUE THREAD

**Issue by Danny-Mus** [Danny-Mus/master-dex#9]
# MD-08: As a PO i want to see or read the pokemons info when i click on it.

## Tasks
What are the tasks/todo's for this user story

- [x] Discuss if this is gona be an new page or somekind of popup. !important;

## Stage 1
- When you click on a pokemon see indepth info of it (Moves, types, weak/strong against, Egg group, Evolution chain, description)
- [x] Display '**Types**'
- [x] Display '**Weight**'
- [x] Display '**Height**'
- [x] Display '**Base experience**'

## Stage 2
- [ ] Display '**Generation**'
- [ ] Display '**Weak/strong against**'
- [ ] Display '**Egg group**'
- [ ] Display '**Evolution chain**'
- [ ] Display '**Description**'
- [ ] Display '**Gender**'
- [ ] Display '**Growth rate**'
- [ ] Display '**stats**'
- [ ] Display '**Moves**'

- Perhaps this could be categorized in tabs.
- [ ] when clicking on a pokemon to see its info.
## Ready for Review?
- You need 2 thumbs off
- Build (code and design) are according to Definition Of Done (see dod.md)
